dag:

  # Config for DAG run
  dag_id: "Train_prod2vec_model"
  default_args:
    owner: "Rich"
    start_date: "2020-10-03"
    end_date: "2020-10-03"
    depends_on_past: False
    retries: 0
    catchup: False
    email: "richjdowney@gmail.com"
    email_on_failure: True
    email_on_retry: False
  schedule_interval: "@once"

s3:

  # Config for s3
  bucket: "instacart-kaggle-data"
  orders_key: "order_products__train.csv"
  products_key: "products.csv"
  couples_list_train_key: "couples_list_train.txt"
  couples_list_valid_key: "couples_list_valid.txt"
  labels_list_train_key: "labels_list_train.txt"
  labels_list_valid_key: "labels_list_valid.txt"
  prod_target_train_key: "prod_target_train.csv"
  prod_target_valid_key: "prod_target_valid.csv"
  prod_context_train_key: "prod_context_train.csv"
  prod_context_valid_key: "prod_context_valid.csv"
  reversed_dict_key: "reversed_dictionary.pkl"
  products_dict_key: "products_dict.pkl"

preprocess_constants:

  # Config for data pre-processing
  num_prods: 10000
  train_ratio: 0.8
  train_window_size: 5


estimator_config:

  # Config for training and tuning estimator
  static_params:
    run_id: '2'
    entry_point: "/home/ubuntu/prod2vec/pipeline/model_train/model_train.py"
    run_hyperparameter_opt: "yes"
    epochs: 100
    num_folds: 5
    valid_size: 100
    valid_window: 1000
    cross_validate: False
    metric_definitions:
    - Name: loss
      Regex: "loss: ([0-9\\.]+)"
    objective_metric_name: "loss"
    objective_type: "Minimize"
  train_hyperparameters:
    embeddings: 400
    learning_rate: 0.1
  tune_hyperparameters:
    max_jobs: 2
    max_parallel_jobs: 2
    min_embeddings: 100
    max_embeddings: 500
    min_learning_rate: 0.01
    max_learning_rate: 0.5
  inputs:
    train: "s3://instacart-kaggle-data"

post_process_config:

  # Config for post processing
  model_artifact: "/home/ubuntu/prod2vec/model_artifact/"

