dag:

  # Config for DAG run
  dag_id: "Train_prod2vec_model"
  default_args:
    owner: "Rich"
    start_date: "2020-10-03"
    end_date: "2020-10-03"
    depends_on_past: False
    retries: 0
    catchup: False
    email: "richjdowney@gmail.com"
    email_on_failure: True
    email_on_retry: False
  schedule_interval: "@once"

s3:

  # Config for s3
  bucket: "instacart-kaggle-data"

preprocess_constants:

  # Config for data pre-processing
  num_prods: 35000
  train_window_size: 4
  num_ns: 4
  max_basket_length: 50

estimator_config:

  # Config for training and tuning estimator
  static_params:
    run_id: '26'
    entry_point: "/home/ubuntu/prod2vec/pipeline/model_train/model_train.py"
    run_hyperparameter_opt: "no"
    epochs: 15
    valid_size: 100
    valid_window: 1000
    batch_size: 128
    metric_definitions:
    - Name: loss
      Regex: "loss: ([0-9\\.]+)"
    objective_metric_name: "loss"
    objective_type: "Minimize"
  train_hyperparameters:
    embeddings: 1024
    learning_rate: 0.001
  tune_hyperparameters:
    max_jobs: 5
    max_parallel_jobs: 5
    min_embeddings: 100
    max_embeddings: 1024
    min_learning_rate: 0.0001
    max_learning_rate: 0.001
  inputs:
    train: "s3://instacart-kaggle-data"

post_process_config:

  # Config for post processing
  model_artifact: "/home/ubuntu/prod2vec/model_artifact/"

